server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9680
          predicates:
            - Path=/auth/**

        - id: hospital-service
          uri: http://localhost:8083
          predicates:
            - Path=/doctors/**
          filters:
            - TokenRelay=

        - id: appointment-service
          uri: http://localhost:8084
          predicates:
            - Path=/appointments/**
          filters:
            - TokenRelay=

jwt:
  secret: your-super-secret-key-must-be-at-least-32-chars-long-12345   # same as auth service
