server:
  port: 8080
spring:
   cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9680
          predicates:
            - Path=/auth/**
            
        - id: hospital_route
          uri: http://localhost:8083
          predicates:
            - Path=/doctor/**
          filters:
            - JwtAuthenticationFilter
            
        - id: appointment_route
          uri: http://localhost:8084
          predicates:
            - Path=/appointment/**
          filters:
            - JwtAuthenticationFilter
