server:
  port: 9680

spring:
  mongodb:
    host: localhost
    port: 27017
    database: auth-db

jwt:
  secret: my-super-secret-key-which-is-long-enough-for-hmac-sha256-1234567890
  expiration: 86400000
