spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth-db
      

server:
  port: 9680

jwt:
  secret: your-super-secret-key-must-be-at-least-32-chars-long-12345
  issuer: http://localhost:9680
  expiration: 86400000  

logging:
  level:
    org.springframework: INFO
    com.example.auth_service: DEBUG
