server:
  port: 9680

spring:
  mongodb:
    host: localhost
    port: 27017
    database: auth-db

jwt:
  secret: your-super-secret-key-must-be-at-least-32-chars-long-12345
  expiration: 86400000
  issuer: http://localhost:9680

logging:
  level:
    org.springframework: INFO
