spring:
  mongodb:
    host: localhost
    port: 27017
    database: hospitaldb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9680

server:
  port: 8083

